# PreCompact Hook: Summarize Conversation
# Summarizes all messages except the last N (default: 5)
# Injects summary as additional context before compaction

param(
    [int]$SkipLast = 5
)

# Error handling
$ErrorActionPreference = "Stop"

try {
    # Get environment variables from Claude Code
    $transcriptPath = $env:CLAUDE_TRANSCRIPT_PATH
    $projectDir = $env:CLAUDE_PROJECT_DIR

    if (-not $transcriptPath) {
        Write-Error "CLAUDE_TRANSCRIPT_PATH environment variable not set"
        exit 1
    }

    if (-not (Test-Path $transcriptPath)) {
        Write-Error "Transcript file not found: $transcriptPath"
        exit 1
    }

    # Log hook start to Summy server
    $hookId = $null
    try {
        $logStartUrl = "http://localhost:3001/api/hooks/log-start"
        $logStartData = @{
            hookName = "PreCompact"
            transcriptPath = $transcriptPath
        } | ConvertTo-Json

        $response = Invoke-RestMethod -Uri $logStartUrl -Method POST -Body $logStartData -ContentType "application/json" -ErrorAction SilentlyContinue
        $hookId = $response.id
    } catch {
        # Non-critical - continue without logging
        Write-Warning "Failed to log hook start: $_"
    }

    # Read transcript
    $transcript = Get-Content -Path $transcriptPath -Raw

    if ([string]::IsNullOrWhiteSpace($transcript)) {
        # Empty transcript - nothing to summarize
        $output = @{
            hookSpecificOutput = @{
                hookEventName = "PreCompact"
                additionalContext = "No conversation history to summarize."
            }
        } | ConvertTo-Json -Depth 10

        Write-Output $output
        exit 0
    }

    # Call summarization CLI
    # Remove `.claude` from path if present (hooks run from .claude directory)
    $actualProjectDir = if ($projectDir -like "*\.claude") {
        (Get-Item $projectDir).Parent.FullName
    } else {
        $projectDir
    }
    $cliPath = Join-Path $actualProjectDir "server\src\cli\summarize-cli.ts"

    if (-not (Test-Path $cliPath)) {
        Write-Error "Summarization CLI not found: $cliPath"
        exit 1
    }

    $startTime = Get-Date

    # Pipe transcript to CLI tool
    $summary = $transcript | npx tsx $cliPath --conversation --skip-last $SkipLast 2>&1

    $duration = ((Get-Date) - $startTime).TotalMilliseconds

    if ($LASTEXITCODE -ne 0) {
        throw "CLI tool failed with exit code $LASTEXITCODE"
    }

    # Log hook completion
    if ($hookId) {
        try {
            $logCompleteUrl = "http://localhost:3001/api/hooks/log-complete"
            $logCompleteData = @{
                id = $hookId
                summary = $summary
                duration = [int]$duration
            } | ConvertTo-Json

            Invoke-RestMethod -Uri $logCompleteUrl -Method POST -Body $logCompleteData -ContentType "application/json" -ErrorAction SilentlyContinue
        } catch {
            Write-Warning "Failed to log hook completion: $_"
        }
    }

    # Format output for Claude Code
    $contextMessage = @"
## Previous Conversation Summary

$summary

---
*Note: Last $SkipLast messages preserved with full detail.*
*Summary generated by Summy's intelligent context manager.*
"@

    $output = @{
        hookSpecificOutput = @{
            hookEventName = "PreCompact"
            additionalContext = $contextMessage
        }
    } | ConvertTo-Json -Depth 10

    Write-Output $output
    exit 0

} catch {
    $errorMessage = $_.Exception.Message

    # Log error
    if ($hookId) {
        try {
            $logErrorUrl = "http://localhost:3001/api/hooks/log-error"
            $logErrorData = @{
                id = $hookId
                error = $errorMessage
            } | ConvertTo-Json

            Invoke-RestMethod -Uri $logErrorUrl -Method POST -Body $logErrorData -ContentType "application/json" -ErrorAction SilentlyContinue
        } catch {
            # Silently ignore logging errors
        }
    }

    # Output error to stderr
    Write-Error "PreCompact hook failed: $errorMessage"
    exit 2  # Exit code 2 = blocking error (prevents hook action)
}
