packages:
  - client
  - server
  - mcp-server
  - rag-server
  - database
  - packages/shared
  - packages/types

ignoredBuiltDependencies:
  - better-sqlite3
  - esbuild
  - hnswlib-node
  - puppeteer
  - sqlite3
  - tree-sitter
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-typescript
