import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    color: '#e2e8f0',
    overflowY: 'auto',
    scrollbarWidth: 'thin',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: '#64748b',
    padding: '40px',
    textAlign: 'center',
  },
  emptyIcon: {
    fontSize: '48px',
    marginBottom: '16px',
    opacity: 0.5,
  },
  emptyText: {
    fontSize: '16px',
    fontWeight: 500,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    borderRadius: '12px',
    backdropFilter: 'blur(4px)',
  },
  loadingCard: {
    backgroundColor: '#1e293b',
    padding: '24px 32px',
    borderRadius: '12px',
    border: '1px solid #334155',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.3)',
  },
  spinner: {
    width: '32px',
    height: '32px',
    border: '3px solid #334155',
    borderTopColor: '#8B5CF6',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  loadingText: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#e2e8f0',
  },
  loadingMessage: {
    fontSize: '12px',
    color: '#94a3b8',
    textAlign: 'center',
  },
  heroSection: {
    display: 'flex',
    alignItems: 'center',
    padding: '16px 20px',
    backgroundColor: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '10px',
    gap: '24px',
    minHeight: '200px',
    flexShrink: 0,
    marginBottom: '8px',
  },
  heroLeft: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    minWidth: '90px',
    flexShrink: 0,
  },
  heroCenter: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'visible',
    minWidth: 0,
  },
  heroActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    minWidth: '90px',
    flexShrink: 0,
  },
  actionButtonCompact: {
    padding: '6px 10px',
    backgroundColor: '#14B8A6',
    border: 'none',
    borderRadius: '6px',
    color: '#fff',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.15s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
  },
  actionButtonSecondaryCompact: {
    padding: '5px 8px',
    backgroundColor: 'transparent',
    border: '1px solid #334155',
    borderRadius: '6px',
    color: '#94a3b8',
    fontSize: '10px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.15s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
  },
  tabBar: {
    display: 'flex',
    gap: '2px',
    padding: '6px 8px',
    backgroundColor: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '10px',
    marginBottom: '8px',
  },
  tabButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '6px 10px',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '6px',
    color: '#94a3b8',
    fontSize: '12px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  tabButtonActive: {
    backgroundColor: '#14B8A620',
    color: '#14B8A6',
  },
  tabContent: {
    padding: '0',
    boxSizing: 'border-box',
  },
  card: {
    backgroundColor: '#1e293b',
    borderRadius: '10px',
    border: '1px solid #334155',
    padding: '12px',
    marginBottom: '8px',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#e2e8f0',
    marginBottom: '12px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  cardIcon: {
    fontSize: '14px',
  },
  infoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
    marginBottom: '12px',
  },
  infoItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  infoLabel: {
    fontSize: '11px',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  infoValue: {
    fontSize: '13px',
    color: '#e2e8f0',
    fontWeight: 500,
  },
  description: {
    fontSize: '12px',
    color: '#94a3b8',
    lineHeight: 1.5,
    margin: 0,
  },
  badgesGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  badge: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 10px',
    backgroundColor: '#14B8A615',
    border: '1px solid #14B8A630',
    borderRadius: '16px',
  },
  badgeIcon: {
    fontSize: '12px',
  },
  badgeName: {
    fontSize: '11px',
    fontWeight: 500,
    color: '#14B8A6',
  },
  recList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  recItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 0',
    borderBottom: '1px solid #33415530',
  },
  recDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
  },
  recText: {
    flex: 1,
    fontSize: '12px',
    color: '#e2e8f0',
  },
  recBadge: {
    fontSize: '10px',
    fontWeight: 600,
    color: '#64748b',
    textTransform: 'uppercase',
  },
  actionsRow: {
    display: 'flex',
    gap: '8px',
  },
  actionButton: {
    flex: 1,
    padding: '10px 16px',
    backgroundColor: '#14B8A6',
    border: 'none',
    borderRadius: '8px',
    color: '#fff',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'opacity 0.15s',
  },
  actionButtonSecondary: {
    flex: 1,
    padding: '10px 16px',
    backgroundColor: 'transparent',
    border: '1px solid #334155',
    borderRadius: '8px',
    color: '#94a3b8',
    fontSize: '12px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  skillRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  skillHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  skillIcon: {
    fontSize: '14px',
  },
  skillName: {
    flex: 1,
    fontSize: '12px',
    fontWeight: 500,
    color: '#e2e8f0',
  },
  skillScore: {
    fontSize: '12px',
    fontWeight: 700,
    fontFamily: "'JetBrains Mono', monospace",
  },
  skillBarBg: {
    height: '6px',
    backgroundColor: '#334155',
    borderRadius: '3px',
    overflow: 'hidden',
  },
  skillBarFill: {
    height: '100%',
    borderRadius: '3px',
    transition: 'width 0.3s ease-in-out',
  },
  emptyCard: {
    padding: '24px',
    textAlign: 'center',
    color: '#64748b',
    fontSize: '13px',
    backgroundColor: '#1e293b',
    borderRadius: '10px',
    border: '1px solid #334155',
  },
  toolGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))',
    gap: '8px',
  },
  toolItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 10px',
    backgroundColor: '#0f172a',
    border: '1px solid #334155',
    borderRadius: '6px',
  },
  toolStatus: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
  },
  toolName: {
    flex: 1,
    fontSize: '11px',
    color: '#e2e8f0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  toolScore: {
    fontSize: '10px',
    fontWeight: 600,
    color: '#64748b',
  },
  probeGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  probeItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 12px',
    backgroundColor: '#0f172a',
    border: '1px solid #334155',
    borderRadius: '6px',
  },
  probeStatus: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    color: '#fff',
    fontWeight: 600,
    flexShrink: 0,
  },
  probeInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flex: 1,
    minWidth: 0,
  },
  probeName: {
    flex: 1,
    fontSize: '12px',
    color: '#e2e8f0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  probeScore: {
    fontSize: '12px',
    fontWeight: 600,
    flexShrink: 0,
  },
  probeLatency: {
    fontSize: '11px',
    color: '#64748b',
    flexShrink: 0,
  },
  filterBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    backgroundColor: '#1e293b',
    borderRadius: '8px',
    marginBottom: '8px',
  },
  filterLabel: {
    fontSize: '12px',
    color: '#64748b',
    marginRight: '4px',
  },
  filterButton: {
    padding: '4px 10px',
    fontSize: '11px',
    fontWeight: 500,
    backgroundColor: 'transparent',
    border: '1px solid #334155',
    borderRadius: '4px',
    color: '#94a3b8',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  filterButtonActive: {
    backgroundColor: '#3b82f6',
    borderColor: '#3b82f6',
    color: '#fff',
  },
  capabilityCard: {
    backgroundColor: '#1e293b',
    borderRadius: '8px',
    border: '1px solid #334155',
    marginBottom: '8px',
    overflow: 'hidden',
    transition: 'all 0.2s',
  },
  capabilityCardActive: {
    borderColor: '#8B5CF6',
    boxShadow: '0 0 12px rgba(139, 92, 246, 0.3)',
  },
  capabilityHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 12px',
    cursor: 'pointer',
    userSelect: 'none',
  },
  capabilityHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  capabilityHeaderRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  capabilityIcon: {
    fontSize: '16px',
  },
  capabilityName: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#e2e8f0',
  },
  capabilityScore: {
    fontSize: '13px',
    fontWeight: 700,
  },
  capabilityPassCount: {
    fontSize: '11px',
    color: '#64748b',
  },
  expandIcon: {
    fontSize: '10px',
    color: '#64748b',
    transition: 'transform 0.2s',
  },
  capabilityBarBg: {
    height: '4px',
    backgroundColor: '#0f172a',
    margin: '0 12px 8px 12px',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  capabilityBarFill: {
    height: '100%',
    borderRadius: '2px',
    transition: 'width 0.3s ease-in-out',
  },
  activeIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '11px',
    color: '#8B5CF6',
    marginLeft: '8px',
  },
  spinnerSmall: {
    width: '10px',
    height: '10px',
    border: '2px solid #8B5CF640',
    borderTopColor: '#8B5CF6',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  activeSpinnerContainer: {
    width: '18px',
    height: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    backgroundColor: '#8B5CF620',
    flexShrink: 0,
  },
  probeList: {
    padding: '0 12px 12px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  probeItemCompact: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 10px',
    borderRadius: '4px',
    border: '1px solid',
  },
  probeStatusSmall: {
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '9px',
    color: '#fff',
    fontWeight: 600,
    flexShrink: 0,
  },
  probeNameCompact: {
    flex: 1,
    fontSize: '11px',
    color: '#e2e8f0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  progressContainer: {
    padding: '16px',
    backgroundColor: '#1e293b',
    borderRadius: '10px',
    border: '1px solid #334155',
    marginBottom: '8px',
  },
  progressHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  progressLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#e2e8f0',
  },
  pulsingDot: {
    width: '8px',
    height: '8px',
    backgroundColor: '#14B8A6',
    borderRadius: '50%',
    animation: 'pulse 1.5s ease-in-out infinite',
  },
  progressStats: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  progressEta: {
    fontSize: '11px',
    color: '#94a3b8',
  },
  progressCount: {
    fontSize: '12px',
    fontWeight: 500,
    color: '#14B8A6',
  },
  progressBarBg: {
    height: '8px',
    backgroundColor: '#334155',
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '8px',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#14B8A6',
    borderRadius: '4px',
    transition: 'width 0.3s ease-in-out',
  },
  progressDetails: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  progressTestIcon: {
    fontSize: '12px',
  },
  progressCurrentTest: {
    fontSize: '11px',
    color: '#94a3b8',
    fontStyle: 'italic',
  },
};
